name: LootTables
main: com.dumptruckman.minecraft.loottables.LootTables
version: maven-version-number
author: dumptruckman

commands:
  loot:
    description: Tests the primary script file
    usage: /<command> {loot table} [recipient]
    permission: loottables.loot
  lootreload:
    description: Clears the loot table cache so changes in yaml files are detected.
    usage: /<command>
    permission: loottables.reload

permissions:
  loottables.*:
    default: OP
    children:
      loottables.loot: true
      loottables.reload: true
  loottables.loot:
    default: OP
  loottables.reload:
    default: OP